"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Menubar from "@/components/menubar/Menubar";
import React from "react";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSidebarOpen, setIsSidebarOpen] = React.useState(true);

  const handleSidebar = () => {
    setIsSidebarOpen((prev) => !prev);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-neutral-100 flex justify-start items-start  max-w-[1850px] mx-auto rounded-md overflow-hidden ">
          <div
            className={`  ${
              isSidebarOpen ? "w-72" : "w-0"
            } duration-300 transition-all overflow-hidden`}>
            <Sidebar />
          </div>
          <div className="w-full">
            <Menubar onClick={handleSidebar} />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
