import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Menubar from "@/components/menubar/Menubar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-start items-start  max-w-[1850px] mx-auto">
          <div className=" w-72">
            <Sidebar />
          </div>
          <div className="w-full">
            <Menubar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
